// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3hGMvSL_OOjDwh0W950Eaeg3_YWx09c',
    appId: '1:909189054077:web:4929a4aee908eaa31ebb14',
    messagingSenderId: '909189054077',
    projectId: 'ecommerce-d207a',
    authDomain: 'ecommerce-d207a.firebaseapp.com',
    storageBucket: 'ecommerce-d207a.appspot.com',
    measurementId: 'G-ES22MNWSM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrwoI0t7CtYmG2lL8DmY8_qkAs3GHaLto',
    appId: '1:909189054077:android:eb586d0dcef714161ebb14',
    messagingSenderId: '909189054077',
    projectId: 'ecommerce-d207a',
    storageBucket: 'ecommerce-d207a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMa23AIXJa6YxU_thC9dhsz1ofM976wG0',
    appId: '1:909189054077:ios:3f405a806ab3905f1ebb14',
    messagingSenderId: '909189054077',
    projectId: 'ecommerce-d207a',
    storageBucket: 'ecommerce-d207a.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMa23AIXJa6YxU_thC9dhsz1ofM976wG0',
    appId: '1:909189054077:ios:3f405a806ab3905f1ebb14',
    messagingSenderId: '909189054077',
    projectId: 'ecommerce-d207a',
    storageBucket: 'ecommerce-d207a.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf3hGMvSL_OOjDwh0W950Eaeg3_YWx09c',
    appId: '1:909189054077:web:b910631e48e7976b1ebb14',
    messagingSenderId: '909189054077',
    projectId: 'ecommerce-d207a',
    authDomain: 'ecommerce-d207a.firebaseapp.com',
    storageBucket: 'ecommerce-d207a.appspot.com',
    measurementId: 'G-RKZX7SNN2L',
  );
}
